/* Generated by Yosys 0.41+111 (git sha1 a84e4f44f, g++ 10.2.1 -fPIC -Os) */

module and2(a, b, c);
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  assign c = 4'h8 >> { a, b };
endmodule
