/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module and2(a, b, c);
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  assign c = 4'h8 >> { a, b };
endmodule
